// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ScanningtestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void scanningtest() {
    driver.get("https://digitalfeet.com/");
    driver.manage().window().setSize(new Dimension(1936, 1096));
    {
      WebElement element = driver.findElement(By.cssSelector("#menu-item-15078 .menu-text"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("#menu-item-15078 .menu-text")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#menu-item-15078 .menu-text"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    js.executeScript("window.scrollTo(0,365)");
    js.executeScript("window.scrollTo(0,624)");
    js.executeScript("window.scrollTo(0,1259)");
    driver.findElement(By.cssSelector(".elementor-element-7b611cd9 .elementor-button-link")).click();
    driver.findElement(By.cssSelector(".elementor-element-66a0bf3 .elementor-button-text")).click();
    js.executeScript("window.scrollTo(0,1561)");
    driver.findElement(By.cssSelector("#premium-carousel-d9a4c26 > .carousel-next > .fas")).click();
    driver.findElement(By.cssSelector("#premium-carousel-d9a4c26 > .carousel-next > .fas")).click();
    driver.findElement(By.cssSelector("#premium-carousel-d9a4c26 > .carousel-next > .fas")).click();
    driver.findElement(By.cssSelector("#premium-carousel-d9a4c26 > .carousel-next > .fas")).click();
    js.executeScript("window.scrollTo(0,2227)");
    js.executeScript("window.scrollTo(0,2737)");
    js.executeScript("window.scrollTo(0,4161)");
    js.executeScript("window.scrollTo(0,5565)");
    driver.findElement(By.cssSelector("#ast-fixed-header .custom-logo")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#ast-fixed-header .custom-logo"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.close();
  }
}
